[versions]
kotlin = "2.2.0"
ktor = "3.2.1"
atomicfu = "0.29.0"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core-linuxx64", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json-linuxx64", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl-linuxx64", version.ref = "ktor" }
ktor-client-content = { module = "io.ktor:ktor-client-content-negotiation-linuxx64", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth-linuxx64", version.ref = "ktor" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu-linuxx64", version.ref = "atomicfu" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
